# Generated by Django 4.2.5 on 2023-10-22 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accesspoint', '0001_initial'),
        ('bss', '0001_initial'),
        ('interface', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interface_metrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_bytes', models.BigIntegerField()),
                ('rx_bytes', models.BigIntegerField()),
                ('tx_fail', models.IntegerField()),
                ('rx_fail', models.IntegerField()),
                ('tx_retry', models.IntegerField()),
                ('rx_retry', models.IntegerField()),
                ('interface_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interface.interface')),
            ],
        ),
        migrations.CreateModel(
            name='Bss_metrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_bytes', models.BigIntegerField()),
                ('rx_bytes', models.BigIntegerField()),
                ('tx_drop', models.IntegerField()),
                ('rx_drop', models.IntegerField()),
                ('bss_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bss.bss')),
            ],
        ),
        migrations.CreateModel(
            name='Accesspoint_metrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_stamp', models.DateTimeField()),
                ('temp', models.DecimalField(decimal_places=2, max_digits=5)),
                ('backhaul_utilisation', models.FloatField()),
                ('total_clients', models.IntegerField()),
                ('ap_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accesspoint.accesspoint')),
            ],
        ),
    ]
