# Generated by Django 4.2.5 on 2023-10-22 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bss',
            fields=[
                ('bss_id', models.IntegerField(primary_key=True, serialize=False)),
                ('ssid_name', models.CharField(max_length=20)),
                ('passphrase', models.CharField(max_length=20)),
                ('security_mode', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('num_clients', models.IntegerField()),
                ('tx_bytes', models.BigIntegerField()),
                ('rx_bytes', models.BigIntegerField()),
                ('tx_errors', models.IntegerField()),
                ('rx_errors', models.IntegerField()),
            ],
        ),
    ]
