# Generated by Django 4.2.5 on 2023-10-11 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessPoints',
            fields=[
                ('OBJECTID', models.IntegerField(primary_key=True, serialize=False)),
                ('Type', models.CharField(default='null', max_length=30, null=True)),
                ('Provider', models.CharField(default='null', max_length=40, null=True)),
                ('Remarks', models.CharField(default='null', max_length=100, null=True)),
                ('SSID', models.CharField(default='null', max_length=25, null=True)),
                ('Activated', models.DateField(default='null', null=True)),
            ],
        ),
    ]
