# Generated by Django 4.2.5 on 2023-10-06 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accesspoints', '0002_remove_accesspoints_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesspoints',
            name='activated',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='accesspoints',
            name='provider',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='accesspoints',
            name='remarks',
            field=models.CharField(default='null', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='accesspoints',
            name='ssid',
            field=models.CharField(default='null', max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='accesspoints',
            name='type',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='accesspoints',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
