# Generated by Django 4.2.5 on 2023-10-25 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accesspoint', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesspoint',
            name='location',
            field=models.CharField(max_length=50),
        ),
    ]
