# Generated by Django 4.2.5 on 2023-10-22 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accesspoint', '0001_initial'),
        ('bss', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interface',
            fields=[
                ('interface_id', models.IntegerField(primary_key=True, serialize=False)),
                ('interface_name', models.CharField(max_length=20)),
                ('interface_type', models.CharField(max_length=20)),
                ('tx_bytes', models.BigIntegerField()),
                ('rx_bytes', models.BigIntegerField()),
                ('tx_errors', models.IntegerField()),
                ('rx_errors', models.IntegerField()),
                ('ap_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accesspoint.accesspoint')),
                ('bss_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bss.bss')),
            ],
        ),
    ]
