# Generated by Django 4.2.5 on 2023-10-06 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sites',
            name='area',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sites',
            name='boro',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='sites',
            name='borocode',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='sites',
            name='boroname',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='sites',
            name='city',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='sites',
            name='council_district',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='sites',
            name='lat',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='sites',
            name='location',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sites',
            name='location_type',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sites',
            name='long',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='sites',
            name='nta',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='sites',
            name='ntacode',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='sites',
            name='x_coord',
            field=models.DecimalField(decimal_places=8, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='sites',
            name='y_coord',
            field=models.DecimalField(decimal_places=8, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='sites',
            name='zipcode',
            field=models.IntegerField(null=True),
        ),
    ]
